# TCL File Generated by Component Editor 18.1
# Thu Mar 17 20:25:21 MST 2022
# DO NOT MODIFY


# 
# hash_avalon_interface "hash_component" v1.0
#  2022.03.17.20:25:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hash_avalon_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME hash_avalon_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Own IP Cores"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hash_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hash
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hash.sv SYSTEM_VERILOG PATH hash.sv TOP_LEVEL_FILE
add_fileset_file sha256.v VERILOG PATH sha256.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hash
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hash.sv SYSTEM_VERILOG PATH hash.sv
add_fileset_file sha256.v VERILOG PATH sha256.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset resetn reset_n Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point avalon_slave_0_1_1
# 
add_interface avalon_slave_0_1_1 avalon end
set_interface_property avalon_slave_0_1_1 addressUnits WORDS
set_interface_property avalon_slave_0_1_1 associatedClock clock_sink
set_interface_property avalon_slave_0_1_1 associatedReset clock_reset
set_interface_property avalon_slave_0_1_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1_1 holdTime 0
set_interface_property avalon_slave_0_1_1 linewrapBursts false
set_interface_property avalon_slave_0_1_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1_1 readLatency 0
set_interface_property avalon_slave_0_1_1 readWaitTime 1
set_interface_property avalon_slave_0_1_1 setupTime 0
set_interface_property avalon_slave_0_1_1 timingUnits Cycles
set_interface_property avalon_slave_0_1_1 writeWaitTime 0
set_interface_property avalon_slave_0_1_1 ENABLED true
set_interface_property avalon_slave_0_1_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1_1 waitrequest waitrequest Output 1
add_interface_port avalon_slave_0_1_1 address address Input 4
add_interface_port avalon_slave_0_1_1 read read Input 1
add_interface_port avalon_slave_0_1_1 readdata readdata Output 32
add_interface_port avalon_slave_0_1_1 write write Input 1
add_interface_port avalon_slave_0_1_1 writedata writedata Input 32
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isPrintableDevice 0

